// Code generated by sum_generator DO NOT EDIT.
package ast

type _gdef interface {
	_gdef() // not exported dummy method
}
func (*VarDeclStmt) _gdef() {}
func (*FuncDef) _gdef() {}

type _expr interface {
	_expr() // not exported dummy method
}
func (*BinaryExpr) _expr() {}
func (*UnaryExpr) _expr() {}
func (*EmptyExpr) _expr() {}
func (*LVal) _expr() {}
func (*FuncCallExpr) _expr() {}
func (*BracketExpr) _expr() {}
func (IntLit) _expr() {}
func (FloatLit) _expr() {}

type _stmt interface {
	_stmt() // not exported dummy method
}
func (*AssignStmt) _stmt() {}
func (*ExprStmt) _stmt() {}
func (*EmptyStmt) _stmt() {}
func (*VarDeclStmt) _stmt() {}
func (*IfStmt) _stmt() {}
func (*WhileStmt) _stmt() {}
func (*BreakStmt) _stmt() {}
func (*ContinueStmt) _stmt() {}
func (*ReturnStmt) _stmt() {}
func (*BlockStmt) _stmt() {}